version: '3.7'
services:
  adminer:
    image: adminer
    ports:
      - 8585:8080
      
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: melior_user
      POSTGRES_PASSWORD: melior_user_password
      POSTGRES_DB: melior_db
     
  localstack:
    image: localstack/localstack
    container_name: localstack_service
    ports:
      - "4567-4584:4567-4584"
      - "8586:8080"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
    volumes:
      - ./tmp/localstack:/tmp/localstack   
      - /var/run/docker.sock:/var/run/docker.sock