#For development purposes
#I'll be using an actual DB in production...

version: '3.1'
services:

  adminer:
    image: adminer
    ports:
      - 8080:8080
      
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: melior_user
      POSTGRES_PASSWORD: melior_user_password
      POSTGRES_DB: melior_db
     
  melior:
    build: .
    depends_on: [ postgres ]
    ports:
      - 8095:8095
    environment:
      - Database:ConnectionString=Host=postgres;Port=5432;Database=melior_db;Username=melior_user;Password=melior_user_password;
