module Server.Authentication.CommonPasswords

let private commonPasswords = 
    [|
        "123456", true
        "welkom", true
        "linkedin", true
        "welkom01", true
        "geheim", true
        "amsterdam", true
        "wachtwoord", true
        "Welkom01", true
        "vakantie", true
        "willem", true
        "feyenoord", true
        "qwerty", true
        "vergeten", true
        "rotterdam", true
        "netwerk", true
        "mercedes", true
        "koffie", true
        "pieter", true
        "konijn", true
        "jeroen", true
        "monique", true
        "computer", true
        "maarten", true
        "password", true
        "vlinder", true
        "marcel", true
        "olifant", true
        "fietsbel", true
        "marianne", true
        "voetbal", true
        "tijger", true
        "liefde", true
        "marieke", true
        "bloemen", true
        "tweeling", true
        "floortje", true
        "Linkedin", true
        "zonnebloem", true
        "johanna", true
        "netwerken", true
        "floris", true
        "tennis", true
        "banaan", true
        "jasper", true
        "rakker", true
        "telefoon", true
        "diesel", true
        "jolanda", true
        "sander", true
        "martin", true
        "dolfijn", true
        "ingrid", true
        "sandra", true
        "dennis", true
        "gerard", true
        "martijn", true
        "000000", true
        "marijke", true
        "kikker", true
        "w8woord", true
        "hendrik", true
        "esther", true
        "groningen", true
        "mickey", true
        "welkom1", true
        "herman", true
        "roosje", true
        "thomas", true
        "78787878", true
        "brandweer", true
        "12345678", true
        "internet", true
        "welkom123", true
        "anneke", true
        "joepie", true
        "fietsen", true
        "winter", true
        "robert", true
        "tommie", true
        "johannes", true
        "linked", true
        "wouter", true
        "test123", true
        "yvonne", true
        "danielle", true
        "linkesoep", true
        "utrecht", true
        "sophie", true
        "simone", true
        "annelies", true
        "janneke", true
        "saartje", true
        "alexander", true
        "bommel", true
        "charlotte", true
        "sinterklaas", true
        "sammie", true
        "LinkedIn", true
        "mirjam", true
        "marloes", true
        "albert", true
        "beertje", true
        "noortje", true
        "123456789", true
        "casper", true
        "barcelona", true
        "feyenoord1", true
        "maandag", true
        "gerrit", true
        "patrick", true
        "blabla", true
        "margriet", true
        "maaike", true
        "kinderen", true
        "pindakaas", true
        "tineke", true
        "olivier", true
        "elisabeth", true
        "Welkom123", true
        "vincent", true
        "pepper", true
        "annemarie", true
        "snoopy", true
        "caroline", true
        "saskia", true
        "marleen", true
        "werken", true
        "linkedin2011", true
        "nijmegen", true
        "1qaz2wsx", true
        "oliebol", true
        "maartje", true
        "peter1", true
        "astrid", true
        "contact", true
        "vandaag", true
        "charlie", true
        "liesbeth", true
        "guusje", true
        "marion", true
        "chantal", true
        "111111", true
        "richard", true
        "zonnetje", true
        "bobbie", true
        "claudia", true
        "succes", true
        "1234567", true
        "eindhoven", true
        "marjolein", true
        "porsche", true
        "citroen", true
        "willem2", true
        "miranda", true
        "judith", true
        "heineken", true
        "martine", true
        "alfaromeo", true
        "kabouter", true
        "jasmijn", true
        "Amsterdam", true
        "madelief", true
        "volvov70", true
        "marlies", true
        "trustno1", true
        "moppie", true
        "michelle", true
        "poekie", true
        "cornelia", true
        "1q2w3e4r", true
        "cornelis", true
        "volkswagen", true
        "sebastiaan", true
        "lekkerding", true
        "toekomst", true
        "aardbei", true
        "marian", true
        "helena", true
        "appels", true
        "toyota", true
        "formule1", true
        "ronald", true
        "Feyenoord1", true
        "Welkom", true
        "nederland", true
        "carmen", true
        "pascal", true
        "muziek", true
        "kareltje", true
        "pietje", true
        "vrienden", true
        "zomerzon", true
        "master", true
        "bastiaan", true
        "paulus", true
        "daantje", true
        "matthijs", true
        "annette", true
        "boomer", true
        "jacqueline", true
        "maxime", true
        "henkie", true
        "sterre", true
        "labrador", true
        "hanneke", true
        "doortje", true
        "wachtwoord1", true
        "maastricht", true
        "yamaha", true
        "zomer2011", true
        "appelsap", true
        "doerak", true
        "tijgertje", true
        "vrijheid", true
        "familie", true
        "barbara", true
        "ijsbeer2010", true
        "holland", true
        "klaproos", true
        "benjamin", true
        "carolien", true
        "bertus", true
        "jansen", true
        "september", true
        "goudvis", true
        "nicole", true
        "ferrari", true
        "daniel", true
        "fleurtje", true
        "mozart", true
        "loesje", true
        "gitaar", true
        "regenboog", true
        "sunshine", true
        "jantje", true
        "kawasaki", true
        "porsche911", true
        "willem1", true
        "abcdef", true
        "hoihoi", true
        "melanie", true
        "marjan", true
        "robbie", true
        "suzanne", true
        "bassie", true
        "angela", true
        "gelukkig", true
        "denhaag", true
        "zeilboot", true
        "garfield", true
        "patricia", true
        "rabobank", true
        "linkedin1", true
        "adriaan", true
        "louise", true
        "sparta", true
        "isabel", true
        "appeltaart", true
        "spanje", true
        "banjer", true
        "newyork", true
        "tristan", true
        "leonie", true
        "sjoerd", true
        "cooper", true
        "brammetje", true
        "michiel", true
        "canada", true
        "eveline", true
        "lodewijk", true
        "valentijn", true
        "kanjer", true
        "kaatje", true
        "mkbsem123", true
        "michel", true
        "bianca", true
        "dribbel", true
        "geertje", true
        "justin", true
        "willemijn", true
        "paarden", true
        "scooby", true
        "klopklop", true
        "gijsje", true
        "Amsterdam1", true
        "sylvia", true
        "wilhelmina", true
        "frankrijk", true
        "linkedin01", true
        "droppie", true
        "evelien", true
        "monster", true
        "vogels", true
        "harley", true
        "stefan", true
        "klootzak", true
        "oranje", true
        "zaq12wsx", true
        "annabel", true
        "grietje", true
        "harrie", true
        "jippie", true
        "adriana", true
        "tarzan", true
        "school", true
        "loekie", true
        "suzuki", true
        "margreet", true
        "mariska", true
        "marathon", true
        "jaguar", true
        "saxofoon", true
        "bikkel", true
        "portugal", true
        "bootje", true
        "quinten", true
        "profile", true
        "teuntje", true
        "catharina", true
        "afrika", true
        "waterman", true
        "renault", true
        "wessel", true
        "geenidee", true
        "maurice", true
        "P@ssw0rd", true
        "kippen", true
        "michael", true
        "666666", true
        "communicatie", true
        "sukkel", true
        "biertje", true
        "jochem", true
        "Welkom2011", true
        "secret", true
        "dibbes", true
        "corrie", true
        "pukkie", true
        "voorjaar", true
        "kruimel", true
        "tulpen", true
        "jacobus", true
        "steenbok", true
        "engeltje", true
        "hallo123", true
        "morris", true
        "vrijdag", true
        "soepkip", true
        "lavendel", true
        "neeltje", true
        "kirsten", true
        "isabelle", true
        "rosalie", true
        "schaap", true
        "picasso", true
        "nienke", true
        "samsung", true
        "renate", true
        "sanne1", true
        "sabine", true
        "hockey", true
        "peugeot", true
        "marielle", true
        "danique", true
        "spetter", true
        "honden", true
        "twingo", true
        "zeilen", true
        "lisanne", true
        "bakker", true
        "natasja", true
        "maxmax", true
        "ducati", true
        "l1nk3d1n", true
        "kuifje", true
        "moeder", true
        "nijntje", true
        "napoleon", true
        "linkedin123", true
        "pepijn", true
        "zomers", true
        "bloemkool", true
        "qwerty12", true
        "geheim01", true
        "kanarie", true
        "xxxxxx", true
        "isabella", true
        "654321", true
        "lieverd", true
        "december", true
        "tamara", true
        "bennie", true
        "klarinet", true
        "boeken", true
        "caravan", true
        "waarom", true
        "paashaas", true
        "philips", true
        "speedy", true
        "snuffie", true
        "abc123", true
        "123123", true
        "sjakie", true
        "frederik", true
        "ajax01", true
        "passat", true
        "margot", true
        "steven", true
        "buster", true
        "geheim1", true
        "stephan", true
        "okidoki", true
        "amsterdam1", true
        "zeeland", true
        "australie", true
        "fender", true
        "amber1", true
        "boris1", true
        "victoria", true
        "lianne", true
        "jemoeder", true
        "Welkom1", true
        "suriname", true
        "appelmoes", true
        "rianne", true
        "janneman", true
        "3kinderen", true
        "1qazxsw2", true
        "prinses", true
        "mexico", true
        "bolletje", true
        "spider", true
        "qwerty123", true
        "123abc", true
        "nelleke", true
        "marijn", true
        "welkom2011", true
        "julian", true
        "voetbal1", true
        "susanne", true
        "carnaval", true
        "bartje", true
        "boerderij", true
        "lekker", true
        "vissen", true
        "welkom12", true
        "1234567890", true
        "landrover", true
        "miriam", true
        "vitesse", true
        "Marianne", true
        "boefje", true
        "sneeuw", true
        "maarten1", true
        "friesland", true
        "Geheim01", true
        "agenda", true
        "hallo1", true
        "augustus", true
        "hotmail", true
        "william", true
        "gandalf", true
        "willem01", true
        "nicolaas", true
        "hennie", true
        "annemieke", true
        "gabber", true
        "junior", true
        "nideknil", true
        "victor", true
        "deventer", true
        "fleur1", true
        "nikita", true
        "marina", true
        "thailand", true
        "brigitte", true
        "pluisje", true
        "pietjepuk", true
        "sharon", true
        "audia4", true
        "mariette", true
        "samsam", true
        "nathalie", true
        "elizabeth", true
        "maxima", true
        "appelboom", true
        "roland", true
        "hardlopen", true
        "appeltje", true
        "thijmen", true
        "Welkom02", true
        "pauline", true
        "binkie", true
        "Feyenoord", true
        "waterpolo", true
        "brutus", true
        "enschede", true
        "grolsch", true
        "zweden", true
        "fiets1", true
        "liesje", true
        "12qwaszx", true
        "bloempje", true
        "amersfoort", true
        "2kinderen", true
        "ginger", true
        "antonia", true
        "tweety", true
        "marieke1", true
        "abcd1234", true
        "dropje", true
        "santiago", true
        "desiree", true
        "W8woord", true
        "trompet", true
        "koelkast", true
        "testtest", true
        "zaterdag", true
        "mazzel", true
        "Monique", true
        "Floortje", true
        "1234qwer", true
        "madelon", true
        "kiekeboe", true
        "123qwe", true
        "annemiek", true
        "loveyou", true
        "radio538", true
        "dominique", true
        "poesje", true
        "jesper", true
        "diederik", true
        "brenda", true
        "karel1", true
        "sterren", true
        "raymond", true
        "sophia", true
        "maria1", true
        "schatje", true
        "heleen", true
        "bloempot", true
        "toscane", true
        "trombone", true
        "corvette", true
        "flappie", true
        "Zomer2011", true
        "jessica", true
        "bergen", true
        "janjan", true
        "maurits", true
        "jeffrey", true
        "paulien", true
        "veerle", true
        "marinus", true
        "hannah", true
        "frank1", true
        "antonius", true
        "welkom02", true
        "tomaat", true
        "mustang", true
        "winnie", true
        "system", true
        "minoes", true
        "katten", true
        "kokkie", true
        "tomtom", true
        "antoinette", true
        "einstein", true
        "merlijn", true
        "carpediem", true
        "florence", true
        "muisje", true
        "herfst", true
        "andrea", true
        "marjon", true
        "rutger", true
        "lonneke", true
        "bengel", true
        "Linkedin1", true
        "dexter", true
        "shadow", true
        "christiaan", true
        "schilder", true
        "Robert", true
        "spirit", true
        "Jolanda1", true
        "dommel", true
        "qwerty1", true
        "marietje", true
        "leiden", true
        "hondje", true
        "roberto", true
        "Linkedin01", true
        "marlboro", true
        "jessie", true
        "Willem", true
        "socialmedia", true
        "korfbal", true
        "karper", true
        "simpel", true
        "laurens", true
        "rudolf", true
        "vlinders", true
        "amerika", true
        "natascha", true
        "twister", true
        "hortensia", true
        "nissan", true
        "denise", true
        "apeldoorn", true
        "angelique", true
        "gertjan", true
        "jannie", true
        "Rotterdam1", true
        "bertje", true
        "volleybal", true
        "corine", true
        "aaaaaa", true
        "kleintje", true
        "nederland1", true
        "walter", true
        "linkeloetje", true
        "marco1", true
        "zonneschijn", true
        "zonnestraal", true
        "lisette", true
        "ricardo", true
        "Rotterdam", true
        "praktijk", true
        "badmuts", true
        "gerben", true
        "esther1", true
        "varken", true
        "verliefd", true
        "monica", true
        "apollo", true
        "haarlem", true
        "nijlpaard", true
        "florian", true
        "hunter", true
        "vliegtuig", true
        "karin1", true
        "timmie", true
        "boterbloem", true
        "advocaat", true
        "samson", true
        "pegasus", true
        "erasmus", true
        "pandora", true
        "kerstboom", true
        "schorpioen", true
        "apekop", true
        "dorien", true
        "alkmaar", true
        "superman", true
        "ingeborg", true
        "litmanen", true
        "handbal", true
        "stephanie", true
        "geertruida", true
        "klavertje4", true
        "spitfire", true
        "jeanne", true
        "koekje", true
        "poezen", true
        "makkelijk", true
        "morgen", true
        "Thomas01", true
        "flipper", true
        "knorretje", true
        "trijntje", true
        "melissa", true
        "potlood", true
        "zakelijk", true
        "claire", true
        "strand", true
        "mireille", true
        "Herfst2011", true
        "terschelling", true
        "schilderij", true
        "mazda323", true
        "toegang", true
        "tijmen", true
        "marije", true
        "sascha", true
        "polleke", true
        "richard1", true
        "daphne", true
        "panter", true
        "wesley", true
        "kayleigh", true
        "vakantie1", true
        "zwembad", true
        "1q2w3e", true
        "afblijven", true
        "zxcvbnm", true
        "wilma1", true
        "vectra", true
        "david1", true
        "alfa156", true
        "tilburg", true
        "joost1", true
        "andries", true
        "duiken", true
        "pinguin", true
        "arnold", true
        "Trustno1", true
        "Johanna", true
        "sterretje", true
        "fiat500", true
        "welkom11", true
        "121212", true
        "ijsvogel", true
        "joris1", true
        "weegschaal", true
        "sleutel", true
        "Linkedin2011", true
        "bridge", true
        "anton1", true
        "gerrie", true
        "eduard", true
        "scooter", true
        "christel", true
        "appelflap", true
        "diamant", true
        "greetje", true
        "bernard", true
        "Amsterdam01", true
        "carlijn", true
        "karlijn", true
        "maureen", true
        "qwerty01", true
        "barend", true
        "muppet", true
        "zwolle", true
        "heracles", true
        "winkel", true
        "gazelle", true
        "julius", true
        "Ingrid", true
        "vriendin", true
        "floor1", true
        "sylvester", true
        "zxcvbn", true
        "genieten", true
        "link123", true
        "qwer1234", true
        "jolanda1", true
        "volvo1", true
        "rodajc", true
        "heerenveen", true
        "Miranda", true
        "regina", true
        "Anneke", true
        "energie", true
        "splinter", true
        "audia3", true
        "Floortje1", true
        "nadine", true
        "jupiter", true
        "nacbreda", true
        "Maarten1", true
        "maserati", true
        "marcel01", true
        "goldwing", true
        "november", true
        "palmboom", true
        "jelmer", true
        "link2011", true
        "volvov50", true
        "minicooper", true
        "maatje", true
        "asdfgh", true
        "kampioen", true
        "almere", true
        "ramses", true
        "hilversum", true
        "afcajax", true
        "christine", true
        "werner", true
        "koekoek", true
        "aardappel", true
        "siemens", true
        "arthur", true
        "johan1", true
        "Marijke", true
        "eekhoorn", true
        "carola", true
        "kimberly", true
        "janine", true
        "frans1", true
        "kruimeltje", true
        "boerenkool", true
        "silvester", true
        "gijsbert", true
        "fabienne", true
        "verjaardag", true
        "jonathan", true
        "beppie", true
        "peter123", true
        "hans01", true
        "abcdefg", true
        "@17181718@", true
        "Jeroen1", true
        "ferdinand", true
        "Utrecht", true
        "juliette", true
        "cleopatra", true
        "pieter1", true
        "donderdag", true
        "hendrika", true
        "starten", true
        "martina", true
        "jeroen1", true
        "babette", true
        "mondeo", true
        "131313", true
        "marcella", true
        "Porsche911", true
        "breezer", true
        "Winter2011", true
        "samantha", true
        "Pieter", true
        "maartje1", true
        "politie", true
        "jacoba", true
        "1234abcd", true
        "patrick1", true
        "zwaantje", true
        "myrthe", true
        "mickey01", true
        "hendrik1", true
        "beatles", true
        "chocolade", true
        "joshua", true
        "hamster", true
        "marijke1", true
        "Lente2011", true
        "contacten", true
        "keuken", true
        "bonnie", true
        "komkommer", true
        "schoen", true
        "letmein", true
        "draakje", true
        "pannekoek", true
        "qwertyuiop", true
        "veronica", true
        "cabrio", true
        "zwabber", true
        "yvette", true
        "tennisbal", true
        "welkom10", true
        "wammes", true
        "Linked", true
        "george", true
        "jeannette", true
        "test1234", true
        "kleinkind", true
        "motormuis", true
        "buurman", true
        "gompie", true
        "silvia", true
        "amstel", true
        "lorenzo", true
        "mazda626", true
        "lobbes", true
        "josephine", true
        "appel1", true
        "thomas1", true
        "robbert", true
        "arnhem", true
        "curacao", true
        "vijver", true
        "beatrix", true
        "zondag", true
        "schaatsen", true
        "hannibal", true
        "wageningen", true
        "reinier", true
        "flower", true
        "billie", true
        "aanmelden", true
        "laguna", true
        "Geheim", true
        "koeien", true
        "oktober", true
        "Willem1", true
        "beethoven", true
        "weetniet", true
        "fcutrecht", true
        "phoenix", true
        "scania", true
        "valerie", true
        "mathijs", true
        "Alexander", true
        "hannes", true
        "thomas01", true
        "skippy", true
        "compaq", true
        "cambuur", true
        "repelsteeltje", true
        "henriette", true
        "ijsbeer", true
        "linkedin.com", true
        "linkedln", true
        "jannes", true
        "abraham", true
        "nellie", true
        "pinkeltje", true
        "ballon", true
        "fietsje", true
        "domino", true
        "knuffel", true
        "tobias", true
        "berend", true
        "colombia", true
        "opelastra", true
        "Welkom11", true
        "jackie", true
        "fransje", true
        "audia6", true
        "iloveyou", true
        "vriend", true
        "disney", true
        "mooiweer", true
        "hummel", true
        "lalala", true
        "suiker", true
        "creative", true
        "voetballen", true
        "berber", true
        "maandag1", true
        "nelson", true
        "scheveningen", true
        "saturnus", true
        "sander01", true
        "boudewijn", true
        "qazwsx", true
        "knabbel", true
        "pebbles", true
        "albatros", true
        "samuel", true
        "doorgaan", true
        "collega", true
        "andreas", true
        "waalwijk", true
        "efteling", true
        "wortel", true
        "meander", true
        "waterval", true
        "tessa1", true
        "Yvonne", true
        "schiphol", true
        "bonaire", true
        "hester", true
        "vitesse1", true
        "roosendaal", true
        "schipper", true
        "mientje", true
        "Herman", true
        "martien", true
        "zonnig", true
        "eureka", true
        "wintersport", true
        "qwerty11", true
        "annemijn", true
        "snoekbaars", true
        "libelle", true
        "janwillem", true
        "7777777", true
        "bond007", true
        "zonnet", true
        "Marieke1", true
        "chester", true
        "Maarten", true
        "stamper", true
        "februari", true
        "mischa", true
        "weekend", true
        "schildpad", true
        "loopbaan", true
        "zomer1", true
        "stones", true
        "computer1", true
        "woerden", true
        "figaro", true
        "xander", true
        "kasper", true
        "444444", true
        "zafira", true
        "twente", true
        "gilles", true
        "Vakantie", true
        "kwaliteit", true
        "voordeur", true
        "django", true
        "marius", true
        "Welkom12", true
    |]
    |> dict

let isCommonPassword password =
    commonPasswords.ContainsKey(password)